### ISSUE TITLE
cannot login / debian jessie

### ISSUE THREAD

**Issue by mstekker** [dieonar/MyMumb-Panel#13]
Hi,

Server mumble servers works well, but cannot login with the web interface.

login as SuperUser with password or any other user won't work. After clicking on connection, nothing happens. User/pwd dissapear and that is it.

Ice socket is available, all configured as stated in the manual.

Any suggestions?

**Comment by dieonar** [comment]
Try to desactive user protection login in config file and try again.

**Comment by invisan** [comment]
@mstekker which version of ice are u using? If its not 3.4.2 it may be the cause like with my problem. Try the solution in the readme of my fork or create your own Murmur.php with this steps (if you are using Linux)

If you have a different ICE Version then 3.4.2 or 3.5.1 you have to create the Murmur.php manually. This can be done on Linux this way:

You have to change the below sections for the ICE Version to fit your directorys and needs.



Change to the inc directory of MyMumbPanel.

cp /usr/share/murmur/Murmur.ice murmur_1.2.5.ice 
slice2php -I/usr/share/Ice-3.5.1/slice/ --ice murmur_1.2.5.ice

(The Path for Ice could differ here. Use the one which fits you. Please leave the -I at the beginning since it specifies the Input)

After that

rm murmur_1.2.5.ice 

You now should have a murmur_1.2.5.ice.php in your folder.

Delete the old Murmur.php or rename it to the Version before and change the Name of your newly created murmur_*.ice.php to Murmur.php

You should now be able to login.
